# Generated by Django 2.2.4 on 2021-10-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('cl1', models.CharField(max_length=10)),
                ('cl2', models.CharField(max_length=30)),
                ('svs', models.CharField(max_length=10)),
                ('kcal', models.CharField(max_length=10)),
                ('protein_g', models.CharField(max_length=10)),
                ('fat_g', models.CharField(max_length=10)),
                ('carbo_g', models.CharField(max_length=10)),
                ('sugar_g', models.CharField(max_length=10)),
                ('calc_mg', models.CharField(max_length=10)),
                ('pota_mg', models.CharField(max_length=10)),
                ('salt_mg', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'foodNutrientsdb',
            },
        ),
    ]
